# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[conda]
disabled = false
ignore_base = false
format = '[$symbol$environment](dimmed green) '

[directory]
truncation_length = 8
truncation_symbol = '…/'

[hostname]
disabled = false
ssh_only = true
format = '[$hostname](bold white)'


[line_break]
disabled = false

[nodejs]
disabled = true

# how can I put time on the line same with conda?
[time]
disabled = true
use_12hr = false
format = '[\[$time\]]($style) '
time_format = '%T'

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true
